loki:
  structuredConfig:
    ingester:
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    storage_config:
      aws:
        endpoint: minio.minio.svc.cluster.local:9000
        insecure: true
        bucketnames: lokistorage
        access_key_id: REDACTED!!
        secret_access_key: REDACTED!!
        s3forcepathstyle: true
      boltdb_shipper:
        shared_store: s3
    schema_config:
      configs:
        - from: 2023-07-06
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

distributor:
  replicas: 1

ingester:
  replicas: 1

querier:
  replicas: 1

queryFrontend:
  replicas: 1

gateway:
  nginxConfig:
    httpSnippet: |-
            client_max_body_size 100M;
    serverSnippet: |-
            client_max_body_size 100M;
